language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - black bert_optimization tests setup.py
  - isort -rc bert_optimization tests setup.py
  - flake8 bert_optimization tests setup.py
  - pytest
