language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - black dyna_bert tests setup.py
  - isort -rc dyna_bert tests setup.py
  - flake8 dyna_bert tests setup.py
  - pytest
